{
 "title": "k6 influxdb 2.X",
 "description": "k6 for influxdb 2.x version(Flux)\r\n",
 "time": { "from": "2024-11-21T14:15:00.000Z", "to": "2024-11-21T14:50:59.000Z" },
 "panels": [
  {
   "title": "Data_received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"data_received\")\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> yield(name: \"data_sent\")"
    }
   ]
  },
  {
   "title": "Data_sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"data_sent\")\r\n  |> aggregateWindow(every: 1m, fn: sum)\r\n  |> yield(name: \"data_sent\")"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "totalRequests = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"errors\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ r with name: \"static _value_errors\" }))\n  |> yield(name: \"static _value_errors\")"
    },
    {
     "query": "totalErrors = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ r with name: \"static _value_requests\" }))\n  |> yield(name: \"static _value_requests\")"
    },
    {
     "query": "totalRequests = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ r with join_key: \"static\" }))\n\ntotalErrors = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"errors\")\n  |> filter(fn: (r) => r._field == \"value\")\n  |> group(columns: [])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ r with join_key: \"static\" }))\n\njoin(\n  tables: {requests: totalRequests, errors: totalErrors},\n  on: [\"join_key\"]\n)\n|> map(fn: (r) => ({\n  r with error_rate: (float(v: int(v: (r._value_errors / r._value_requests) * 10000.0)) / 100.0)\n}))\n|> keep(columns: [\"_time\", \"error_rate\"])  // Оставляем только _time и error_rate\n|> yield(name: \"error_rate\")"
    }
   ]
  },
  {
   "title": "http_reqs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [])\r\n  |> aggregateWindow(every: 1s, fn: count)\r\n  |> yield(name: \"http_reqs_count\")"
    }
   ]
  },
  {
   "title": "vus(Virtual Users)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "vus(Virtual Users)_max",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus_max\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "http_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_duration\")\r\n"
    }
   ]
  },
  {
   "title": "http_req_receiving",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_receiving\")"
    }
   ]
  },
  {
   "title": "http_req_waiting",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_waiting\")"
    }
   ]
  },
  {
   "title": "http_req_sending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 37 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_sending\")\r\n  "
    }
   ]
  },
  {
   "title": "Http_req_blocked-TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_blocked\")"
    }
   ]
  },
  {
   "title": "http_req_connecting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"scenario\", \"url\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\r\n  |> yield(name: \"max_http_req_connecting\")"
    }
   ]
  },
  {
   "title": "http_req_tls_handshaking",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "\tfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}